name: flutter_ajanuw_android_pip
description: Set picture-in-picture mode on Android
version: 0.1.2
homepage: https://github.com/januwA/flutter_android_pip

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ajanuw.flutter_android_pip
        pluginClass: FlutterAndroidPipPlugin